
#try:
    # hata olabilecek blok 

#except:
    #hata mesajı

try:
    a = int(input("sayı 1 : "))
    b = int(input("sayı 2 : "))
    print(a+b)

except:
    print("hata oluştu.")